# 1- Fondamentaux du Python

## a) Dictionnaires et tuples

### Créez un tuple qui associe votre login à votre âge

In [1]:
login_age=('stoupin', 31)

### Initialisez un dictionnaire à deux entrées qui associe le login de chacun de vos voisins à leur âge

In [2]:
login_by_age = {'emarin': 20, 'spajeo': 31, 'pchoffe': 56}

### Récupérez l'âge de l'un d'entre eux à partir du dictionnaire

In [4]:
login_by_age['emarin']

20

### Ajoutez une entrée avec votre propre login

In [5]:
login_by_age['stoupin'] = 31

## b) Manipulation de listes

### Créez une liste A contenant les entiers suivants: 1, 3, 2, 7, 4, 10, 46

In [23]:
A = [1, 3, 2, 7, 4, 10, 46]
A

[1, 3, 2, 7, 4, 10, 46]


### Affichez les 3 premiers éléments de la liste A - en une ligne de code

In [7]:
A[:3]

[1, 3, 2]

### Créez une liste B qui contient seulement les 3e, 4e et 5e éléments de A . Votre ligne de code ne devrait contenir que 8 caractères (sans compter les espaces) - Vérifiez bien votre résultat!

In [24]:
B = A[3:6]
B

[7, 4, 10]

### Concaténez les listes A et B pour former la liste C

In [25]:
C = A + B
C

[1, 3, 2, 7, 4, 10, 46, 7, 4, 10]

### Ajoutez le nombre 5 à la liste A

In [26]:
A += [5]
A

[1, 3, 2, 7, 4, 10, 46, 5]

### Ajoutez un élément nul à la liste C

In [27]:
C += [None]
C

[1, 3, 2, 7, 4, 10, 46, 7, 4, 10, None]

## b) Fonctions

### Écrivez une fonction qui prend comme arguments une liste 'lst' et un entier 'n' et retourne le résultat de n concaténations de 'lst' avec elle-même (ex: lst=[1,2,3], n=2 --> [1,2,3,1,2,3])

In [31]:
def repeat_list(lst, n):
    result = []
    for i in range(n):
        result += lst
    return result
repeat_list([1, 2, 3], 2)

[1, 2, 3, 1, 2, 3]

### Vous voulez rendre le paramètre 'n' optionnel et fixer sa valeur à 2 par défaut. Comment faites-vous?

In [33]:
def repeat_list_2(lst, n = 2):
    return repeat_list(lst, n)
repeat_list_2([1, 2, 3])

[1, 2, 3, 1, 2, 3]

## c) Boucles

### Avec une boucle 'while', imprimez chaque élément de la liste C jusqu'à l'élément nul

In [34]:
i = 0
while C[i] is not None:
    print(C[i])
    i += 1

1
3
2
7
4
10
46
7
4
10


### Calculez, avec une boucle 'for', le nombre d'entiers pairs présents dans la liste A

In [35]:
count = 0
for elem in A:
    if elem % 2 == 0:
        count += 1
count

4

### Réécrivez l'expression suivante avec une boucle 'for' sur plusieurs lignes

In [ ]:
C = [element for element in A if element %2 == 0]

In [36]:
C = []
for element in A:
    if element % 2 == 0:
        C.append(element)
C

[2, 4, 10, 46]

# 2- Opérations sur matrices avec numpy

### Transformer les listes A et B en tableaux numpy a et b

In [44]:
import numpy as np
a = np.array(A)
b = np.array(B)
print('a', a)
print('b', b)

a [ 1  3  2  7  4 10 46  5]
b [ 7  4 10]


### Concaténez-les pour former un tableau c (a, b --> c)

In [55]:
c = np.hstack([a, b])
c

array([ 1,  3,  2,  7,  4, 10, 46,  5,  7,  4, 10])

### Divisez tous les éléments de c par 3 (sans utiliser de boucle)

In [56]:
c = np.divide(c, 3)
c

array([ 0.33333333,  1.        ,  0.66666667,  2.33333333,  1.33333333,
        3.33333333, 15.33333333,  1.66666667,  2.33333333,  1.33333333,
        3.33333333])

### Calculez la somme de tous les éléments de c (sans utiliser de boucle)

In [57]:
c.sum()

33.0

### Exécutez les trois cellules suivantes pour visualiser les matrices M et N

In [58]:
M = np.random.randint(10, size=(4,4))
N = np.random.randint(10, size=(4,4))

In [59]:
M

array([[0, 3, 9, 0],
       [6, 9, 8, 7],
       [9, 4, 0, 2],
       [8, 7, 4, 8]])

In [60]:
N

array([[9, 9, 2, 1],
       [5, 9, 1, 3],
       [7, 9, 0, 3],
       [6, 5, 5, 0]])

### Aditionnez les deux matrices

In [61]:
M + N

array([[ 9, 12, 11,  1],
       [11, 18,  9, 10],
       [16, 13,  0,  5],
       [14, 12,  9,  8]])

### Calculez le produit matriciel de M et N. Vérifiez votre opération en calculant les premières cellules à la main

In [65]:
np.dot(M, N)

array([[ 78, 108,   3,  36],
       [197, 242,  56,  57],
       [113, 127,  32,  21],
       [183, 211,  63,  41]])

### ** Bonus: Écrivez vous-mêmes une fonction de produit matriciel, avec des boucles imbriquées 

In [75]:
def matmult(A, B):
    m, n = A.shape
    o, p = B.shape
    if n != o:
        raise Exception('dimension mismatch')
    result = np.zeros((m, p))
    for i in range(m):
        for j in range(p):
            for k in range(n):
                result[i, j] += A[i, k] * B[k, j]
    return result
A = np.random.randint(10, size = (3, 2))
B = np.random.randint(10, size = (2, 4))
C = matmult(A, B)
print(A)
print(B)
print(C)
print(np.dot(A, B))

[[2 2]
 [2 6]
 [6 3]]
[[9 7 1 4]
 [6 9 8 1]]
[[30. 32. 18. 10.]
 [54. 68. 50. 14.]
 [72. 69. 30. 27.]]
[[30 32 18 10]
 [54 68 50 14]
 [72 69 30 27]]


### ** Comparez son temps de calcul à la fonction de numpy avec de très grosses matrices en entrée

In [78]:
from time import time
A = np.random.randint(10, size = (1337, 1337))
B = np.random.randint(10, size = (1337, 1337))
t0 = time()
C = np.dot(A, B)
t1 = time()
t1 - t0

17.16896414756775